using System.Reflection;
using System.Text.Json.Nodes;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.DependencyInjection;
using ModelContextProtocol.Server;
using MtgMcp.App.Capabilities;
using MtgMcp.Decks;
using MtgMcp.Statistics;

namespace MtgMcp.App.Statistics;

/// <summary>
/// Owns the exact statistics surface and its explicit schema-enriched registration.
/// </summary>
internal static class StatisticsToolsetManifest
{
    /// <summary>
    /// Lists every closed-union discriminator published by this toolset.
    /// </summary>
    private static readonly HashSet<string> DiscriminatorValues = new(StringComparer.Ordinal)
    {
        "raw",
        "deck",
        "entry-ids",
        "zone-names",
        "category-ids",
        "exactly",
        "zero",
        "at-least",
        "at-most",
        "range",
        "hypergeometric-at-least",
        "turn-at-least",
        "mana-availability",
    };

    /// <summary>
    /// Defines the exact public tool assignment and default relevance.
    /// </summary>
    internal static CapabilityToolsetDescriptor Descriptor { get; } = new(
        CapabilityToolset.Stats,
        CapabilityToolsetStability.Stable,
        "Provider-independent exact mathematics over caller-supplied groups and explicitly selected deck populations.",
        [
            "stats_deck_summary",
            "stats_hypergeometric",
            "stats_mana_availability",
            "stats_minimum_count",
            "stats_mulligan",
            "stats_multivariate",
            "stats_package_assembly",
            "stats_turn_table",
        ],
        [],
        []);

    /// <summary>
    /// Registers exactly eight read-only tools for every operation mode.
    /// </summary>
    internal static void Register(
        IMcpServerBuilder builder,
        SqliteDeckStore deckStore,
        ExactStatisticsCalculator calculator)
    {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentNullException.ThrowIfNull(deckStore);
        ArgumentNullException.ThrowIfNull(calculator);
        StatisticsReadTools target = new(new StatisticsDeckResolver(deckStore), calculator);
        builder.WithTools(
        [
            Create(nameof(StatisticsReadTools.HypergeometricAsync), target),
            Create(nameof(StatisticsReadTools.MultivariateAsync), target),
            Create(nameof(StatisticsReadTools.TurnTableAsync), target),
            Create(nameof(StatisticsReadTools.ManaAvailabilityAsync), target),
            Create(nameof(StatisticsReadTools.PackageAssemblyAsync), target),
            Create(nameof(StatisticsReadTools.MulliganAsync), target),
            Create(nameof(StatisticsReadTools.MinimumCountAsync), target),
            Create(nameof(StatisticsReadTools.DeckSummaryAsync), target),
        ]);
    }

    /// <summary>
    /// Creates one explicitly named tool with discriminator descriptions.
    /// </summary>
    private static McpServerTool Create(string methodName, StatisticsReadTools target)
    {
        MethodInfo method = typeof(StatisticsReadTools).GetMethod(
            methodName,
            BindingFlags.Instance | BindingFlags.NonPublic)!;
        return McpServerTool.Create(method, target, new McpServerToolCreateOptions
        {
            SchemaCreateOptions = new AIJsonSchemaCreateOptions
            {
                TransformSchemaNode = static (_, schema) => DescribeDiscriminator(schema),
                TransformOptions = new AIJsonSchemaTransformOptions
                {
                    TransformSchemaNode = static (_, schema) => DescribeDiscriminator(schema),
                },
            },
        });
    }

    /// <summary>
    /// Explains synthetic polymorphic discriminator constants generated by the schema library.
    /// </summary>
    private static JsonNode DescribeDiscriminator(JsonNode schema)
    {
        if (schema is JsonObject schemaObject &&
            schemaObject["const"] is JsonValue constant &&
            constant.TryGetValue(out string? value) &&
            value is not null &&
            DiscriminatorValues.Contains(value))
        {
            schemaObject["description"] = "Selects the exact closed statistics input variant.";
        }

        return schema;
    }
}
